---
# tasks file for mesh-universal-cp

- name: Install Global Control Plane
  block:
    - name: Copy Kuma-CP Service
      ansible.builtin.template:
        src: "{{ sysd_service }}.j2"
        dest: "/etc/systemd/system/{{ sysd_service }}"

    - name: Copy Mesh License 
      ansible.builtin.copy:
        src: "{{ kmesh_license_path }}"
        dest: /home/kuma/license.json
        owner: kuma 
        group: kuma 
        mode: '0644'
      when: kmesh_license_path != ""

    - name: Systemd Tasks
      include_tasks: "{{ playbook_dir }}/tasks/systemd/systemd-start.yaml"
      vars: 
        service: "{{ sysd_service }}"
  become: true