---
- hosts: all
  vars:
    global_cp_service: "kuma-cp.service"
    zone_cp_service: "kuma-zone-cp.service"
    dp_service: "kuma-dp.service"
    ingress_service: "kuma-ingress.service"
    egress_service: "kuma-egress.service"
    global_cp_addr: "{{ global_cp['addr'] }}"
  vars_files:
    - "{{ kuma_vars_file }}"
  
  tasks:
  - name: Install Kuma Requirements
    ansible.builtin.import_role:
      name: mesh-reqs
    vars:
      kong_version: "{{ kong_mesh_version }}"

  - name: Install Kong Mesh Global CP
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-cp.yaml
    vars:
      kmesh_license_path: "{{ license_path }}"
      sysd_service: "{{ global_cp_service }}"
    when: inventory_hostname in groups["kuma-global-cp"]

  - name: Push Mesh-Policies to Kong Mesh Global CP
    ansible.builtin.copy:
      src: mesh-policies/
      dest: /home/kuma/mesh-policies/
      owner: kuma
      group: kuma
      mode: u=rw,g=r,o=r
    become: yes
    when: inventory_hostname in groups["kuma-global-cp"]
  
  - name: Install Universal Zone CP
    ansible.builtin.include_tasks: 
      file: tasks/mesh/mesh-universal-zone-cp.yaml
    vars:
      sysd_service: "{{ zone_cp_service }}" 
      kong_version: "{{ kong_mesh_version }}"
      kmesh_license_path: "{{ license_path }}"
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
    when: inventory_hostname in groups["kuma-zone-cp"]
  
     
  - name: Install Universal Ingress
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-ingress.yaml
    vars:
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
      sysd_service: "{{ ingress_service }}"
    when: inventory_hostname in groups["kuma-zone-ingress"]
  
  - name: Install Universal Egress
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-egress.yaml
    vars:
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
      sysd_service: "{{ egress_service }}"
    when: inventory_hostname in groups["kuma-zone-ingress"]

  - name: Install Universal Kong Gateway Dataplane
    ansible.builtin.include_tasks: 
      file: tasks/mesh/mesh-universal-dp.yaml
    vars: 
      dataplane: "{{ dataplanes | selectattr('dp_type', 'eq', 'gateway') | first }}"
      sysd_service: "{{ dp_service }}"
    when: inventory_hostname in groups["gateway"]
  
  - name: Install Universal Monolith Dataplane
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-dp.yaml
    vars: 
      dataplane: "{{ dataplanes | selectattr('name', 'eq', 'monolith') | first }}"
      sysd_service: "{{ dp_service }}"
    when: inventory_hostname in groups["monolith"]
