---
## Play 1 OnPrem
- hosts: all
  vars:
    global_cp_service: "kuma-cp.service"
    zone_cp_service: "kuma-zone-cp.service"
    dp_service: "kuma-dp.service"
    ingress_service: "kuma-ingress.service"
    egress_service: "kuma-egress.service"
    global_cp_addr: "{{ global_cp['addr'] }}"
  vars_files:
    - vars/kuma.yml.personal
  
  tasks:
  - name: Install Kuma Requirements
    ansible.builtin.import_role:
      name: mesh-reqs
    vars:
      kong_version: "{{ kong_mesh_version }}"

  - name: Install Kong Mesh Global CP
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-cp.yaml
    vars:
      kmesh_license_path: "{{ license_path }}"
      sysd_service: "{{ global_cp_service }}"
    when: inventory_hostname in groups["kuma-global-cp"]
  
  - name: Install Universal Zone CP
    ansible.builtin.include_tasks: 
      file: tasks/mesh/mesh-universal-zone-cp.yaml
    vars:
      sysd_service: "{{ zone_cp_service }}" 
      kong_version: "{{ kong_mesh_version }}"
      kmesh_license_path: "{{ license_path }}"
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
    when: inventory_hostname in groups["kuma-zone-cp"]
  
     
  - name: Install Universal Ingress
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-ingress.yaml
    vars:
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
      sysd_service: "{{ ingress_service }}"
    when: inventory_hostname in groups["kuma-zone-ingress"]
  
  - name: Install Universal Egress
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-egress.yaml
    vars:
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
      sysd_service: "{{ egress_service }}"
    when: inventory_hostname in groups["kuma-zone-ingress"]

  - name: Install Universal Kong Gateway Dataplane
    ansible.builtin.include_tasks: 
      file: tasks/mesh/mesh-universal-dp.yaml
    vars: 
      dataplane: "{{ dataplanes | selectattr('name', 'eq', 'gateway') | first }}"
      sysd_service: "{{ dp_service }}"
    when: inventory_hostname in groups["gateway"]
  
  - name: Install Universal Monolith Dataplane
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-dp.yaml
    vars: 
      dataplane: "{{ dataplanes | selectattr('name', 'eq', 'monolith') | first }}"
      sysd_service: "{{ dp_service }}"
    when: inventory_hostname in groups["monolith"]

###Play2 Cloud 
- hosts: localhost 
  gather_facts: false
  connection: local
  vars:
    global_cp_addr: "{{ global_cp['addr'] }}"
  vars_files:
    - vars/kuma.yml.personal

  tasks:
  - name: Install K8s Cloud Zone and Microservices
    block: 
    - name: Install K8s Based Zone CP/Ingress/Egress 
      ansible.builtin.include_tasks: 
        file: tasks/mesh/mesh-k8s.yaml
      vars:
        kong_version: "{{ kong_mesh_version }}"
        zone: "{{ item }}"
      loop: "{{ zones | selectattr('type', 'eq', 'k8s') | list }}"
  
    - name: Create Microservice Namespace
      kubernetes.core.k8s:
          state: present
          definition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: microservice
              labels:
                kuma.io/sidecar-injection: enabled

    - name: Run Microservice Deployment
      kubernetes.core.k8s:
        state: present
        src: kuberentes/microservice.yaml
        namespace: microservice

    module_defaults: 
      kubernetes.core.k8s:
        kubeconfig: "{{ kube_config }}"
        clusterconext: "{{ cluster_context }}"
