---
- hosts: all
  vars:
    global_cp_service: "kuma-cp.service"
    zone_cp_service: "kuma-zone-cp.service"
    dp_service: "kuma-dp.service"
    ingress_service: "kuma-ingress.service"
    egress_service: "kuma-egress.service"
  vars_files:
    - vars/kuma.yml
  
  tasks:
  - name: Install Kuma Requirements
    ansible.builtin.import_role:
      name: mesh-reqs
    vars:
      kong_version: "{{ kong_mesh_version }}"

  - name: Install Kong Mesh Global CP
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-cp.yaml
    vars:
      kmesh_license_path: "{{ license_path }}"
      sysd_service: "{{ global_cp_service }}"
    when: inventory_hostname in groups["kuma-global-cp"]
  
  - name: Install Universal Zone CP
    ansible.builtin.include_tasks: 
      file: tasks/mesh/mesh-universal-zone-cp.yaml
    vars:
      sysd_service: "{{ zone_cp_service }}" 
      global_cp_addr: "{{ global_cp['addr'] }}"
      kong_version: "{{ kong_mesh_version }}"
      kmesh_license_path: "{{ license_path }}"
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
    when: inventory_hostname in groups["kuma-zone-cp"]
  
     
  - name: Install Universal Ingress
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-ingress.yaml
    vars:
      global_cp_addr: 54.215.37.158
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
      sysd_service: "{{ ingress_service }}"
    when: inventory_hostname in groups["kuma-zone-ingress"]
  
  - name: Install Universal Egress
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-egress.yaml
    vars:
      global_cp_addr: 54.215.37.158
      zone: "{{ zones | selectattr('type', 'eq', 'universal')  | selectattr('host', 'eq', inventory_hostname) | first }}"
      sysd_service: "{{ egress_service }}"
    when: inventory_hostname in groups["kuma-zone-ingress"]

  - name: Install Universal Kong Gateway Dataplane
    ansible.builtin.include_tasks: 
      file: tasks/mesh/mesh-universal-dp.yaml
    vars: 
      global_cp_addr: 54.215.37.158
      dataplane: "{{ dataplanes | selectattr('name', 'eq', 'gateway') | first }}"
      sysd_service: "{{ dp_service }}"
    when: inventory_hostname in groups["gateway"]

  
  - name: Install Universal Monolith Dataplane
    ansible.builtin.include_tasks:
      file: tasks/mesh/mesh-universal-dp.yaml
    vars: 
      global_cp_addr: 54.215.37.158
      dataplane: "{{ dataplanes | selectattr('name', 'eq', 'monolith') | first }}"
      sysd_service: "{{ dp_service }}"
    when: inventory_hostname in groups["monolith"]
