---
- hosts: all
  vars_files:
    - vars/kuma.yml.personal

  tasks:
  - name: Setup Docker and Python 3.6 VEnv
    ansible.builtin.include_tasks:
      file: tasks/ec2-reqs.yaml
  
  - name: Install Runtime Instance 
    ansible.builtin.import_role:
      name: runtime-instance
    vars:
      ansible_python_interpreter: /opt/ansible_venv/bin/python
    when: inventory_hostname in groups["gateway"]
  
  - name: Install Monolith
    ansible.builtin.include_tasks:
      file: tasks/start-docker.yaml
    vars: 
      container_name: monolith
      image_tag: "{{ monolith_image_tag }}"
      ansible_python_interpreter: /opt/ansible_venv/bin/python
    when: inventory_hostname in groups["monolith"]