---
- hosts: all
  vars_files:
    -  "{{ kuma_vars_file }}"

  tasks:
  - name: Install Pre-requisites
    include_tasks: tasks/ec2-reqs.yaml
  
  - name: Install Konnect Runtime Instance
    include_tasks: tasks/konnect/konnect-cert.yaml
    when: inventory_hostname in groups["gateway"]
  
  - name: Install Monolith
    include_tasks: tasks/start-docker.yaml
    vars: 
      container_name: monolith
      image_tag: "{{ monolith_image_tag }}"
    when: inventory_hostname in groups["monolith"]