---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: djfreese/disputes:latest
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  selector:
    app: microservice
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      appProtocol: http
      port: 8080
      targetPort: 8080

