---
# tasks file for engress-install

- name: Install Egress Dataplane
  block:
    - name: Create Egress Tokens
      include_tasks: "{{ playbook_dir }}/tasks/mesh/token/create-zone-token.yaml"
      vars:
        global_control_plane: "{{ global_cp_addr }}"
        token_type: egress
        zone_name: "{{ zone['name'] }}"

    - name: "Put {{ token_type | upper }} Tokens on Filesystem"
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/tokens/{{ zone.name }}-{{ token_type }}.token"
        dest: "/home/kuma/{{ token_type }}.token"
        owner: kuma 
        group: kuma
        mode: '0644'
        force: true
      vars:
        token_type: egress
    
    - name: "Copy the {{ sysd_service }} Services"
      ansible.builtin.template: 
        src: "{{ sysd_service }}.j2"
        dest: "/etc/systemd/system/{{ sysd_service }}"
      vars:
        zone_cp_hostname: "{{ zone['zone_cp_addr'] }}"
            
    - name: Copy Egress Dataplane Manifests 
      ansible.builtin.template: 
        src: "dataplane-egress.yaml.j2"
        dest: "/home/kuma/dataplane-egress.yaml"
        owner: kuma 
        group: kuma 
        mode: '0644'
      vars: 
        dp_addr: "{{ zone['dp_addr'] }}"

    - name: Start Egress Systemd
      include_tasks: "{{ playbook_dir }}/tasks/systemd/systemd-start.yaml"
      vars: 
        service: "{{ sysd_service }}"
  become: true