---
# tasks file for mesh-zone-cp
- debug:
   msg: "Zone CP being installed : {{ zone }}"

- name: Migrate Postgres DB
  ansible.builtin.shell:
    cmd: /home/kuma/mesh/kong-mesh-1.8.1/bin/kuma-cp migrate up
  environment:
    KUMA_STORE_TYPE: postgres 
    KUMA_STORE_POSTGRES_HOST:  '{{ zone.db.host }}'
    KUMA_STORE_POSTGRES_PORT: '{{ zone.db.port }}' 
    KUMA_STORE_POSTGRES_USER: '{{ zone.db.user }}' 
    KUMA_STORE_POSTGRES_PASSWORD: '{{ zone.db.pass }}'  
    KUMA_STORE_POSTGRES_DB_NAME: '{{ zone.db.name }}'
  become: yes
         
- name: Install Universal Zone on Host
  block:
    - name: Copy Kuma-Zone-CP Service
      ansible.builtin.template: 
        src: "{{ playbook_dir }}/templates/{{ sysd_service }}.j2"
        dest: "/etc/systemd/system/{{ sysd_service }}"
      vars: 
        zone_name: '{{ zone.name }}'
        global_hostname: '{{ global_cp_addr }}'
        postgres_hostname: '{{ zone.db.host }}'
        postgres_port: '{{ zone.db.port }}'
        postgres_user: '{{ zone.db.user }}'
        postgres_password: '{{ zone.db.pass }}'
        postgres_db_name: '{{ zone.db.name }}'

    - name: Copy Mesh License 
      ansible.builtin.copy:
        src: '{{ kmesh_license_path }}'
        dest: /home/kuma/license.json
        owner: kuma 
        group: kuma 
        mode: '0644'

    - name: Systemd Tasks
      ansible.builtin.include_role: 
        name: systemd
      vars:
        service: "{{ sysd_service }}"
  become: true
  when: 
    - zone['type'] is defined 
    - zone['type'] == 'universal'