---
#this is just to have handy, not used in the demo

apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: echo-server
    spec:
      containers:
      - image: jmalloc/echo-server
        imagePullPolicy: Always
        name: echo-server
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    8080.service.kuma.io/protocol: http
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/path: /echo
    konghq.com/plugins: add-response-header
  name: echo-service
spec:
  ports:
  - name: http-port
    port: 8080
    protocol: TCP
    targetPort: http-port
  selector:
    app: echo-server
  sessionAffinity: None
  type: ClusterIP