license_path: "<path>"
kong_mesh_version: 1.8.1
kube_config: "<path>"
cluster_context: "<cluster-context>"

konnect_password: "<password>"
konnect_username: "<username>"
konnect_controlPlane: "<cp-id>"

global_cp:
  addr: 54.215.37.158

zones:
  - name: "cloud"
    type: "k8s"
    kube_config: "<path>"
    cluster_context: "<cluster-context>"
    chart_version: 1.8.2
  - name: "on_prem"
    type: "universal"
    host: 54.193.67.206
    zone_addr: 10.0.0.7
    ingress:
      host: 54.193.67.206
      install: true
      dp_addr: 10.0.0.7
      dp_advertised_ip: 54.193.67.206
    egress: 
      install: true
      host: 54.193.67.206
      dp_addr: 10.0.0.7
  
dataplanes:
  - name: "gateway"
    dp_type: "gateway"
    zone_type: "universal"
    zone_addr: 10.0.0.7
    dp_manifest:
      outbound:
        tags: 
          kuma_service: monolith-service_default_svc_5000
  - name: "monolith"
    dp_type: "standard"
    zone_type: "universal"
    zone_addr: 10.0.0.7
    dp_manifest:
      inbound:
        port: 5000
        svc_port: 8080
        tags:
          kuma_service: monolith-service_default_svc_5000
          
  - name: "microservice"
    dp_type: "standard"
    zone_type: "k8s"
    deployment_file: "vars/TODO"

  