FROM hashicorp/terraform:latest

COPY ./terraform_infra/ /kmj

# run init to ensure we have everything required and lay down directory structures
RUN cd /kmj && \
    terraform init && \
    mkdir -p /kmj/out/{ansible,tf}

WORKDIR /kmj
