---
- name: "Create {{ token_type | upper }} Token"
  block: 
    - name: "Check if {{ token_type }} Token exists"
      ansible.builtin.stat:
        path: '/home/kuma/{{ zone_name }}-{{ token_type }}.token'
      register: st_token
    
    - name: "Create {{ token_type | upper }} Token"
      ansible.builtin.shell: "/usr/local/bin/kumactl generate zone-token --zone {{ zone_name }} --valid-for 720h --scope {{ token_type }} > /home/kuma/{{ zone_name }}-{{ token_type }}.token"
      when: not st_token.stat.exists or st_token.stat.size == 0
    
    - name: "Get {{ token_type | upper }} Token"
      ansible.builtin.shell: "cat /home/kuma/{{ zone_name }}-{{ token_type }}.token"
      register: token_result

    - name: "Fetch {{ token_type | upper }} from Global CP to Bastion"
      ansible.builtin.fetch: 
        src: "/home/kuma/{{ zone_name }}-{{ token_type }}.token"
        dest: "{{ playbook_dir }}/tokens/{{ zone_name }}-{{ token_type }}.token"
        flat: yes
  run_once: true
  delegate_to: "{{ global_control_plane }}"